# render.yaml — Tells Render how to deploy the backend

services:
  - type: web
    name: ai-risk-auth-api
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python ml/generate_csv.py && python ml/train_model.py"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false